### ISSUE TITLE
This is not an issue, this is a thank you!

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [dgreene1/tsoa-koa-example-with-typeorm#11]
I was having trouble setup my controller so it would accept my JSON Payload, and I saw in your code, that the interface defining params simply had to be the interface of the Model, excluding properties that are not expected as params

so thaaank you ! :D ;)

**Comment by dgreene1** [comment]
Thank you for sharing your gratitude @Jean-Baptiste-Lasselle. That’s so uncommon in these times. I really appreciate it. Thank you for being a part of the tsoa community. :)
